
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-happycows-s24-4pm-6
owner: ucsb-cs156-s24
repo_name: proj-happycows-s24-4pm-6
pull_requests: [{"author":{"id":"U_kgDOBXuvjg","is_bot":false,"login":"emanbareket","name":""},"headRefName":"Immanuel-DeleteButton","number":61,"title":"Announcements Delete Button","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-6/pull/61"},{"author":{"id":"U_kgDOBXuvjg","is_bot":false,"login":"emanbareket","name":""},"headRefName":"Immanuel-EditButton","number":57,"title":"Announcements edit button","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-6/pull/57"}]
