
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-happycows-s24-4pm-6
owner: ucsb-cs156-s24
repo_name: proj-happycows-s24-4pm-6
pull_requests: [{"author":{"id":"U_kgDOB740jQ","is_bot":false,"login":"sawyerrice","name":""},"headRefName":"Sawyer-HC-pagedProfits","number":28,"title":"dont merge","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-6/pull/28"},{"author":{"id":"MDQ6VXNlcjg5NTU1MzQw","is_bot":false,"login":"nbelle1","name":"Nik Belle"},"headRefName":"Nik-RemoveUser-Frontend","number":27,"title":"Admin can remove user from commons - FRONTEND DO NOT MERGE","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-6/pull/27"},{"author":{"id":"MDQ6VXNlcjI0NzgzNDE3","is_bot":false,"login":"dakotazoid56","name":"Dakota"},"headRefName":"Dakota-DeleteUserFromCommon-Bug","number":25,"title":"Dakota - Fix CommonsController delete bug","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-6/pull/25"},{"author":{"id":"MDQ6VXNlcjI0NzgzNDE3","is_bot":false,"login":"dakotazoid56","name":"Dakota"},"headRefName":"Dakota-LeaveCommons-Backend","number":24,"title":"(2nd) Dakota Add Backend to Leave Button Home Page","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-6/pull/24"},{"author":{"id":"MDQ6VXNlcjI0NzgzNDE3","is_bot":false,"login":"dakotazoid56","name":"Dakota"},"headRefName":"Dakota-LeaveCommons-Button","number":23,"title":"Dakota Add frontend Leave Button to Home Page","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-6/pull/23"},{"author":{"id":"MDQ6VXNlcjg5NTU1MzQw","is_bot":false,"login":"nbelle1","name":"Nik Belle"},"headRefName":"Nik-RemoveUser-Backend","number":22,"title":"Admin can remove user from commons - BACKEND","url":"https://github.com/ucsb-cs156-s24/proj-happycows-s24-4pm-6/pull/22"}]
