name: "30-frontend-tests: JavaScript, Jest Unit tests"

on:
  workflow_dispatch:
  pull_request:
    paths: [frontend/**, .github/workflows/30-frontend-tests.yml]
  push:
    branches: [main]
    paths: [frontend/**, .github/workflows/30-frontend-tests.yml]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/Los_Angeles"
      - uses: actions/checkout@v3.5.2
        with: 
          fetch-depth: 2
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: 'frontend/package.json'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - run: npm ci
        working-directory: ./frontend
      - run: npm test
        working-directory: ./frontend
    
